name: welive
services:
  db:
    image: postgres:15-alpine
    container_name: welivedb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=welivedb
    ports:
      - "5432:5432" # 로컬의 5432 포트로 접속 허용
    volumes:
      - ./postgres_data:/var/lib/postgresql/data # 데이터 휘발 방지 (로컬에 저장)

volumes:
  postgres_data: