name: EC2 배포
on:
  push:
    branches: ["main", "feature/gy/deploy"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # environment: production

    steps:
      - name: 1. 코드 가져오기
        # 현재 리포지토리의 소스 코드를 가상 서버로 내려받음
        uses: actions/checkout@v4

      - name: 2. Node.js 설정
        # Node.js 실행 환경 구축
        uses: actions/setup-node@v4
        with:
          # 24 버전 사용
          node-version: '24'
          # 캐시를 사용해 다음 배포 때 설치 속도 향상
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'

      - name: 3. 빌드 확인
        run: |
          cd backend
          # package-lock.json에 명시된 정확한 버전의 라이브러리 설치
          npm ci 
          # Prisma 클라이언트 코드 생성
          npx prisma generate
          # 프로젝트 빌드를 실행하여 문법 오류 확인
          npm run build


      - name: 4. SSH 접속 및 배포
        run: |
          # 가상 환경에 SSH 접속을 위한 개인키 설정
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa # 키 파일 권한 보안 설정
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts # 서버를 신뢰할 수 있는 호스트로 등록 (접속 시 Yes/No 묻는 단계 방지)
          
          # EC2 서버에 원격 접속 시작
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e # 명령어 실패시 즉시 스크립트 중단
            
            # NVM의 설치 경로를 환경 변수로 정의
            export NVM_DIR="$HOME/.nvm"
            # nvm.sh 스크립트 파일이 존재하는지 확인한 뒤, 존재하면 현재 셸에 실행
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # 서버 내 프로젝트 폴더로 이동
            cd ~/welive-backend
          
            # 최신 코드 동기화
            git fetch origin
            git checkout ${{ github.ref_name }} # 현재 푸시된 브랜치로 전환
            git pull origin ${{ github.ref_name }} # 최신 코드 가져오기
          
            cd backend
            npm install # 서버 환경에 필요한 라이브러리 설치/업데이트
          
            npx prisma generate # 서버 환경용 Prisma 코드 생성
            npm run build # 서버에서 최신 코드로 빌드 실행

            # PM2를 이용한 무중단 서비스 재시작
            if pm2 describe welive > /dev/null; then
              # 이미 'welive'라는 프로세스가 실행 중이면 설정값 갱신하여 재시작
              pm2 restart welive --update-env
            else
              # 처음 배포하는 경우라면 새로운 프로세스 시작
              pm2 start tsx --name "welive" -- src/server.ts
            fi
            # 서버 재시작 시 PM2가 자동 실행되도록 현재 상태 저장
            pm2 save
          EOF