export type ApartmentRequest = {
  id: string;
  name: string;
  address: string;
  officeNumber: string;
  description: string;
  startComplexNumber: string;
  endComplexNumber: string;
  startDongNumber: string;
  endDongNumber: string;
  startFloorNumber: string;
  endFloorNumber: string;
  startHoNumber: string;
  endHoNumber: string;
  apartmentStatus: 'APPROVED' | 'PENDING' | 'REJECTED';
  adminId: string;
  adminName: string;
  adminContact: string;
  adminEmail: string;
};
